version: '3.9'

services:
  web:
    build: ./back
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./back:/app
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  cron:
    build: ./back/cron
    volumes:
      - ./back/scripts:/var/www
      - ./back/log/cron:/var/log/cron
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app

volumes:
  mysql-data:
